name: john_deere_spa
description: John Deere Challenge Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  awesome_icons: ^1.1.0
  build_runner: ^2.2.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.0
  mobx_codegen: ^2.0.7+3
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/jhon_logo.gif
    - assets/images/john_logo2.gif
